from sqlalchemy import text
from app.db.session import SessionLocal

async def execute_raw_sql(query: str):
    """
    Executes a raw read-only SQL query generated by the AI.
    """
    async with SessionLocal() as session:
        try:
            # Wrap string in text() for SQLAlchemy
            stmt = text(query)
            result = await session.execute(stmt)
            
            # Fetch all rows and convert to list of dicts (JSON serializable)
            keys = result.keys()
            rows = result.fetchall()
            return [dict(zip(keys, row)) for row in rows]
            
        except Exception as e:
            print(f"SQL Execution Error: {e}")
            return None