# app/cubes/referral_snapshot.py

NAME = "Referral Network Snapshot"
DESCRIPTION = "Tracks the current state, network size, and all-time lifetime totals of a partner's community."
HAS_TIME_FIELD = False
TIME_COLUMN = None
KIND = "df"

# 1. DDL
DDL = """
CREATE TABLE public.ads_total_root_referral_volume_df (
    -- ROOT USER INFO (The Partner)
    root_user_code STRING,      -- Unique Partner ID
    root_country STRING,
    root_user_type STRING,
    
    -- NETWORK SIZE
    total_referrals BIGINT,     -- Total network size (all time)
    invited_registrants BIGINT, -- Indirect + Direct invites
    active_referrals BIGINT,    -- Referrals who actually traded
    active_deposit_users BIGINT,-- Referrals who deposited
    
    -- NETWORK VOLUME (The "Community")
    total_community_volume DOUBLE, -- Root + Referrals Volume
    total_community_trades BIGINT,
    community_volume_last_24h DOUBLE,
    community_volume_yesterday DOUBLE,
    
    -- REFERRAL ONLY METRICS (Commission Basis)
    total_referral_volume DOUBLE,  -- Volume generated by referrals ONLY
    total_referral_trades BIGINT,
    referral_futures_volume DOUBLE,
    referral_spot_volume DOUBLE,
    referral_volume_last_24h DOUBLE,
    referral_volume_yesterday DOUBLE,
    
    -- FINANCIALS & PnL
    total_deposit_amount DOUBLE,   -- Total deposits by referrals
    total_pnl DOUBLE,              -- Net Profit/Loss of referrals
    pnl_yesterday DOUBLE,
    pnl_last_24h DOUBLE,
    
    -- ROOT ACTIVITY (The Partner's own stats)
    root_own_volume DOUBLE,
    root_own_trades BIGINT,
    active_trading_days BIGINT,
    avg_daily_trades DOUBLE,
    
    -- PARTITION
    ds STRING                      -- Date Partition 'YYYYMMDD'
);
"""

# 2. Documentation
DOCS = """
**Table Purpose:**
Used for finding Partner ALL-TIME totals, lifetime metrics, and the current state of their network.

** ⚡ ROUTING RULE (CRITICAL):**
- Use this table ONLY when asked for "Total", "Lifetime", "All-time", or "Current" stats.
- DO NOT use this table if the user asks for a trend or a specific timeframe (e.g., "Last 7 days" or "in February").

**Critical Logic:**
1. **Partition:** Because this is a `_df` (Snapshot) table, you MUST ALWAYS use `ds = '{latest_ds}'`. NEVER use `ds >=` or range filters on this table.
2. **Data Types:** `root_user_code` is a STRING. Always wrap specific partner IDs in quotes (e.g., `WHERE root_user_code = '10000047'`).
3. **Active Ratio:** Calculated as `active_referrals / total_referrals`.
4. **Referral vs Community:** "Referral" metrics exclude the partner's own trading. "Community" metrics include the partner + their referrals.
"""

# 3. Training Examples
EXAMPLES = [
    {
        "question": "Who are the top 10 partners by total referral volume?",
        "sql": """
        SELECT root_user_code, total_referral_volume
        FROM public.ads_total_root_referral_volume_df
        WHERE ds = '{latest_ds}'
        ORDER BY total_referral_volume DESC
        LIMIT 10;
        """
    },
    {
        "question": "What is the active referral ratio for each partner?",
        "sql": """
        SELECT root_user_code, active_referrals, total_referrals,
               (CAST(active_referrals AS DOUBLE) / NULLIF(total_referrals, 0)) AS active_ratio
        FROM public.ads_total_root_referral_volume_df
        WHERE ds = '{latest_ds}' AND total_referrals > 0
        ORDER BY active_ratio DESC;
        """
    },
    {
        "question": "Which countries have the highest referral volume?",
        "sql": """
        SELECT root_country, SUM(total_referral_volume) AS country_referral_volume
        FROM public.ads_total_root_referral_volume_df
        WHERE ds = '{latest_ds}'
        GROUP BY root_country
        ORDER BY country_referral_volume DESC;
        """
    },
    {
        "question": "List partners with more Futures volume than Spot volume.",
        "sql": """
        SELECT root_user_code, referral_futures_volume, referral_spot_volume
        FROM public.ads_total_root_referral_volume_df
        WHERE ds = '{latest_ds}'
        AND referral_futures_volume > referral_spot_volume
        ORDER BY referral_futures_volume DESC;
        """
    },
    {
        "question": "Find partners who have referrals but no trading activity yet.",
        "sql": """
        SELECT root_user_code, total_referrals, total_referral_trades
        FROM public.ads_total_root_referral_volume_df
        WHERE ds = '{latest_ds}'
        AND total_referrals > 0
        AND total_referral_trades = 0;
        """
    },
    {
        "question": "Show the current community volume and active referrals for partner 10000047.",
        "sql": """
        SELECT total_community_volume, active_referrals
        FROM public.ads_total_root_referral_volume_df
        WHERE ds = '{latest_ds}'
          AND root_user_code = '10000047';
        """
    }
]