# app/cubes/referral_performance.py

NAME = "Referral Performance Cube"
DESCRIPTION = "Tracks root partner performance, referral volumes, community size, and commission-related metrics."

# 1. DDL
DDL = """
CREATE TABLE public.ads_total_root_referral_volume_df (
    -- ROOT USER INFO (The Partner)
    root_user_code STRING,      -- Unique Partner ID
    root_country STRING,
    root_user_type STRING,
    
    -- NETWORK SIZE
    total_referrals BIGINT,     -- Total network size (all time)
    invited_registrants BIGINT, -- Indirect + Direct invites
    active_referrals BIGINT,    -- Referrals who actually traded
    active_deposit_users BIGINT,-- Referrals who deposited
    
    -- NETWORK VOLUME (The "Community")
    total_community_volume DOUBLE, -- Root + Referrals Volume
    total_community_trades BIGINT,
    community_volume_last_24h DOUBLE,
    community_volume_yesterday DOUBLE,
    
    -- REFERRAL ONLY METRICS (Commission Basis)
    total_referral_volume DOUBLE,  -- Volume generated by referrals ONLY
    total_referral_trades BIGINT,
    referral_futures_volume DOUBLE,
    referral_spot_volume DOUBLE,
    referral_volume_last_24h DOUBLE,
    referral_volume_yesterday DOUBLE,
    
    -- FINANCIALS & PnL
    total_deposit_amount DOUBLE,   -- Total deposits by referrals
    total_pnl DOUBLE,              -- Net Profit/Loss of referrals
    pnl_yesterday DOUBLE,
    pnl_last_24h DOUBLE,
    
    -- ROOT ACTIVITY (The Partner's own stats)
    root_own_volume DOUBLE,
    root_own_trades BIGINT,
    active_trading_days BIGINT,
    avg_daily_trades DOUBLE,
    
    -- PARTITION
    ds STRING                      -- Date Partition 'YYYYMMDD'
);
"""

# 2. Documentation
DOCS = """
**Table Purpose:**
Used to track Partner/Affiliate performance. Key distinction:
- **Referral Metrics:** Activity done by people the partner invited (Excludes the partner). Use these for commission calculations.
- **Community Metrics:** Activity done by the Partner + Their Referrals combined.
- **Root User:** The partner at the top of the tree.

**Critical Logic:**
1. **Partition:** Always filter by `ds = '{latest_ds}'` for the latest snapshot.
2. **Active Ratio:** Calculated as `active_referrals / total_referrals`.
3. **High Value Partners:** Look for high `total_referral_volume` and `active_deposit_users`.
"""

# 3. Training Examples (Dynamic Date)
EXAMPLES = [
    {
        "question": "Who are the top 10 partners by total referral volume?",
        "sql": """
        SELECT root_user_code, total_referral_volume
        FROM public.ads_total_root_referral_volume_df
        WHERE ds = '{latest_ds}'
        ORDER BY total_referral_volume DESC
        LIMIT 10;
        """
    },
    {
        "question": "What is the active referral ratio for each partner?",
        "sql": """
        SELECT root_user_code, active_referrals, total_referrals,
               (CAST(active_referrals AS DOUBLE) / NULLIF(total_referrals, 0)) AS active_ratio
        FROM public.ads_total_root_referral_volume_df
        WHERE ds = '{latest_ds}' AND total_referrals > 0
        ORDER BY active_ratio DESC;
        """
    },
    {
        "question": "Which countries have the highest referral volume?",
        "sql": """
        SELECT root_country, SUM(total_referral_volume) AS country_referral_volume
        FROM public.ads_total_root_referral_volume_df
        WHERE ds = '{latest_ds}'
        GROUP BY root_country
        ORDER BY country_referral_volume DESC;
        """
    },
    {
        "question": "List partners with more Futures volume than Spot volume.",
        "sql": """
        SELECT root_user_code, referral_futures_volume, referral_spot_volume
        FROM public.ads_total_root_referral_volume_df
        WHERE ds = '{latest_ds}'
        AND referral_futures_volume > referral_spot_volume
        ORDER BY referral_futures_volume DESC;
        """
    },
    {
        "question": "Find partners who have referrals but no trading activity yet.",
        "sql": """
        SELECT root_user_code, total_referrals, total_referral_trades
        FROM public.ads_total_root_referral_volume_df
        WHERE ds = '{latest_ds}'
        AND total_referrals > 0
        AND total_referral_trades = 0;
        """
    }
]